name: desafio_mobile_dev
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # conexión a http
  dio: ^4.0.6
  flutter:
    sdk: flutter
  # base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # vista de imagenes
  photo_view: ^0.14.0
  # gestor de estado
  provider: ^6.0.3
  # preferencias de usuario
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  # para generar el modelo de la base de datos hive
  build_runner: ^2.2.1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
